---
# tasks file for ansible-qualys-cloud-agent

- name: Download the installer
  shell: 'wget {{qualys_agent_dl_location}}'

- name: Run the Install
  shell: 'sudo rpm -ivh {{ qualys_agent_filename }}'
  sudo: true

- name: Activate Qualys
  shell: '/usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId={{ qualys_agent_activationid }} CustomerId={{ qualys_agent_customerid }}'
  sudo: true
